# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Alvaro Perez-Diaz
degree: PhD
title: Dr. Alvaro Perez-Diaz
email: a.perez-diaz (at) soton (dot) ac (dot) uk
description: >
  Personal website
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> and based on <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: alvaropp
linkedin_username: alvaro-perez-diaz
scholar_authorid: EQCORCgAAAAJ
contact_note: feel free to contact me via email!
google_analytics:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: myBlog
blog_description: no-description

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: alvaropp # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  adventures:
    output: true
    permalink: /adventures/:path/
  
news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
plugins:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Perez-Diaz

  group_by: type
  type_order: [article,inproceedings,misc,dataset]

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
